### ISSUE TITLE
Missing lib folder

### ISSUE THREAD

**Issue by Venan24** [HASHSTACS-admin/STACS-SDK#1]
To build project with maven you need: `com.hashstacs:stacs-base:jar:2.1.0` and `com.hashstacs.client:stacs-bm:jar:2.1.1` which are located in `lib` folder and your `lib` is in `.gitignore` so I'm unable to build it.

**Comment by jinser** [comment]
Hi @Venan24 ! 
Thanks for reaching out! 
Yes, those 2 jar files are sent offline to technical partners who have reached out to us with a plan to work on our blockchain.

**Comment by Venan24** [comment]
@jinser Can you please update your `README.md` that will tell users that statement so I can close this issue.

**Comment by jinser** [comment]
@Venan24  yes we have updated the Readme instructions under Pre-Requisites.
